# -*- coding: utf-8 -*-
"""Tarea_8.9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-XTC3_TZ4a4gTDXYk5aK2kLEry_iVxLQ

# Tarea 8.9

En clase introducimos una fórmula para la segunda derivada usando tres evaluaciones de la función. Use la expansión en Taylor de $f(x_o + h)$, $f(x_o - h)$, $f(x_o + 2h)$ y $f(x_o - 2h)$ para encontrar una fórmula para la segunda derivada con cinco evaluaciones y estime el error cometido (la potencia de $h$).

# Repuesta:

Al igual como lo hizo el profesor en los apuntes de clases, expresamos las expansiones en Taylor para cada punto.

* para $f(x_o + h)$ :

$$
f(x_o + h) = f(x_o) + f'(x_o)h + \frac{1}{2}f''(x_o)h^2 + \frac{1}{6}f^{(3)}(x_o)h^3 + \frac{1}{24}f^{(4)}(\xi)h^4
$$

* para $f(x_o - h)$ :

$$
f(x_o - h) = f(x_o) - f'(x_o)h + \frac{1}{2}f''(x_o)h^2 - \frac{1}{6}f^{(3)}(x_o)h^3 + \frac{1}{24}f^{(4)}(\xi)h^4
$$

De la misma forma que antes debemos obtener para $f(x_o + 2h)$ y $f(x_o - 2h)$

* para $f(x_o + 2h)$ :

$$
f(x_o + 2h) = f(x_o) + f'(x_o)2h + f''(x_o)2h^2 + \frac{4}{3}f^{(3)}(x_o)h^3 + \frac{2}{3}f^{(4)}(\xi)h^4
$$

* para $f(x_o - 2h)$ :

$$
f(x_o + 2h) = f(x_o) - f'(x_o)2h + f''(x_o)2h^2 - \frac{4}{3}f^{(3)}(x_o)h^3 + \frac{2}{3}f^{(4)}(\xi)h^4
$$

Para hacer los "paso a paso" más sencillos de ver, vamos a separar las sumas de los puntos en dos.
* primera suma:

$$
f(x_o + h) + f(x_o - h) = 2f(x_o) + f''(x_o)h^2 + \frac{1}{12}f^{(4)}(\xi)h^4\
$$

* segunda suma:

$$
f(x_o + 2h) + f(x_o - 2h) = 2f(x_o) + 4f''(x_o)h^2 + \frac{4}{3}f^{(4)}(\xi)h^4\
$$

Ahora ya que obtuvimos las dos sumas, volvemos a sumar y despejamos $f''(x_o)$ 

$$
f(x_o + h) + f(x_o - h) + f(x_o + 2h) + f(x_o - 2h) = 4f(x_o) + 5f''(x_o)h^2 + \frac{17}{12}f^{(4)}(\xi)h^4\,
$$

Despejamos $ f''(x_o) $

$$
f''(x_o) = \frac{1}{5h^2}\left(f(x_o + h)+ f(x_o + 2h) - 2f(x_o) + f(x_o - h) + f(x_o - 2h)\right) - \frac{17}{12}f^{(4)}(\xi)h^2
$$

De esto mismo podemos notar que tiene un error igual a $ \frac{17}{12}f^{(4)}(\xi)h^2$
"""